# -*- coding: utf-8 -*-
"""score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R0rSqGom_7wCihcani7URDwN3rjAVM_O
"""

score = input().split()
count = 0
sum=0
for i in score:
  sum+=int(i)
  if int(i) < 60:
    count = count + 1
average=sum/len(score)
print("不及格人數：",count)
print("平均分為：",average)

+